spring:
 datasource:
   driver-class-name: com.mysql.jdbc.Driver
   url: jdbc:mysql://127.0.0.1:3306/hqjg
   username: root
   password: a1cf116
   sql-script-encoding: utf-8
   # 下面为连接池的补充设置，应用到上面所有数据源中
   # 初始化大小，最小，最大
   # dbcp:
#      initial-size: 5
#      min-idle: 5
#      max-active:  20
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      max-wait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      time-between-eviction-runs-millis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 300000
#      validation-query: SELECT 1 FROM DUAL
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
#      # 打开PSCache，并且指定每个连接上PSCache的大小
#      pool-prepared-statements: true
#---
#spring:
# profiles: development
# datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    url: jdbc:mysql://127.0.0.1:3306/hqjg
#    username: root
#    password: a1cf116
#    driver-class-name: com.mysql.jdbc.Driver
#---
#spring:
# profiles: production
#datasource:
#    type: com.alibaba.druid.pool.DruidDataSource
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/hqjg
#    username: root
#    password: a1cf116

---
# Set the file size limit (default 1Mb). If you want to specify that files be
# unlimited set the multipart.maxFileSize property to -1.
spring:
  http:
    multipart:
      max-file-size: "50MB"
      max-request-size: "50MB"
---
spring:
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enable: true
        encoding.force: true
---
info:
  app_name: HQJG
  app_version: V1.0
---
server:
  session:
    cookie:
      secure: true
      http-only: false
      domain: "localhost"
---
  server:
    port: 10111
---
 mybatis:
  mapperLocations: "classpath*: com/hqjg/mapper/*.xml"
  typeAliasesPackage: org.hqjg.domain

---
